AppServer:
  Port: "8081"
  ServiceName: "payment-service"
  ServiceVersion: "1.0.0"

Database:
  Host: "postgres"
  Port: 5432
  Name: "payment"
  User: "postgres"
  Password: "AdminPassword123"

Cache:
  Host: "redis"
  Port: 6379
  Database: 1

Kafka:
  Broker: "kafka:9092"
  LoanTopic: "loan-topic"
  PaymentTopic: "payment-topic"
  Timeout: 10
