global:
  scrape_interval: 60s
  scrape_timeout: 10s
  evaluation_interval: 60s

scrape_configs:
  - job_name: prometheus
    honor_labels: true
    honor_timestamps: true
    scheme: http
    scrape_interval: 60s
    scrape_timeout: 55s
    metrics_path: /metrics
    static_configs:
      - targets: ['localhost:9090']